whitelist_5p_v1: /opt/share/software/packages/cellranger-9.0.1/bin/lib/python/cellranger/barcodes/737K-august-2016.txt



marker_filters:
  min_dp: 10
  max_dp: 80
  min_qual: 30
  min_alt_ratio: 0.3
  max_alt_ratio: 0.7


# Stage 3 cell QC thresholds
cell_qc:
  # Genotype call thresholds (per-marker AF cutoffs)
  ref_low: 0.2       # alt_ratio < this -> REF call (genotype 0)
  alt_high: 0.8      # alt_ratio > this -> ALT call (genotype 1)
  # Cell quality filters (primary tier)
  min_total_markers: 2500
  min_per_chrom_markers: 100
  max_switch_rate: 0.09



# Stage 3d CO calling parameters (Meng's defaults for Rhynchospora)
co_calling:
  cell_markers: 2500    # match upstream cell selection threshold
  block_size: 2000000   # 2 Mb min block size
  marker_num: 30         # min markers per block. used to be 8 , raised based on marker support distribution, we tried 50, misse dsome real co now trying 30
